homeassistant:
  # Name of the location where Home Assistant is running
  name: Home Akos
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 352
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Bucharest
  customize:
   switch.neon:
    icon: mdi:lightbulb
# Show links to resources in log and frontend
#introduction:

logger:
  default: warning
#  logs:
#    homeassistant.components: info
#    homeassistant.components.rfxtrx: debug
#    homeassistant.components.device_tracker: critical
#    homeassistant.components.camera: critical

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
#  server_host: 127.0.0.1
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google


group: !include groups.yaml

automation: !include automations.yaml

sensor: !include sensors.yaml

climate: !include climates.yaml

camera: !include cameras.yaml

switch:
  - platform: rpi_gpio
    ports:
      5: Neon
      17: Kazan
      18: Konyha
      27: Nappali
      22: Halo
      23: Test
      24: Gyerekek
      25: Furdo
    invert_logic: true
  - platform: wake_on_lan
    name: "kolgep"
    mac_address: "74:D4:35:0A:6C:F1"

input_boolean:
  notify_home:
    name: Fűtésrednszer kapcsolója
    initial: off
    icon: mdi:fire

zone: 
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 150
  icon: mdi:home

zone 2:
  name: Work
  latitude: !secret latitude2
  longitude: !secret longitude2
  radius: 100
  icon: mdi:worker

zone 3:
  name: Ovi
  latitude: !secret latitude3
  longitude: !secret longitude3
  radius: 50
  icon: mdi:account-multiple

zone 4:
  name: Filo
  latitude: !secret latitude4
  longitude: !secret longitude4
  radius: 100
  icon: mdi:book-open-page-variant

mqtt:
 broker: 127.0.0.1
 port: 1883
 client_id: home-asistant
 keepalive: 60
 username: akos
 password: !secret api_password

device_tracker:
  - platform: owntracks
  - platform: nmap_tracker
    hosts: 10.2.2.30-40
